Homework11: Valeria Kudelko
ValeriaKudelko/Valeria-Kudelko pull request #11
Opened 2024-06-14 10:28 UTC by ValeriaKudelko

2024-06-16 09:51 UTC, Stml89 requested changes

2024-06-16 09:51 UTC, Stml89 commented on hw11task1.py
> +user1.borrow_book(book1)
user1 can take a book, but why user2 can return it?
```suggestion
user1.borrow_book(book1)
user2.return_book(book1)
```

2024-06-16 09:51 UTC, Stml89 commented on hw11task1.py
> +class User:
`reserve` functionality is missing

2024-06-17 17:42 UTC, Stml89 commented
Fix errors in the "Pycodestyle" check

2024-06-20 21:08 UTC, Stml89 requested changes

2024-06-20 21:08 UTC, Stml89 commented on .pylintrc
> +good-names=False
are you sure you need to exclude this check?

2024-06-22 12:51 UTC, ValeriaKudelko commented on .pylintrc
> +good-names=False
deleted

2024-06-22 22:11 UTC, Stml89 approved these changes

2024-06-23 07:56 UTC, merged