Feature/homework6
ValeriaKudelko/Valeria-Kudelko pull request #4
Opened 2024-05-12 14:17 UTC by ValeriaKudelko

2024-05-14 13:50 UTC, Stml89 requested changes
Stiil an issue with pylint, please fix it

2024-05-14 13:50 UTC, Stml89 commented on firstfile.py
> +Sq = 'www.my_site.com#about'.replace('#', '/')
please read this PEP - https://peps.python.org/pep-0008/#descriptive-naming-styles

2024-05-14 13:50 UTC, Stml89 commented on secondfile.py
> +zu1 = []
you do not need empty list creation

2024-05-14 15:22 UTC, ValeriaKudelko commented on secondfile.py
> +zu1 = []
corrected

2024-05-15 20:57 UTC, Stml89 approved these changes

2024-05-15 21:59 UTC, merged